// src/constants.js
export const CREATURE_EMOJIS = {
  'Common Bunny': '🐰',
  'Nutty Squirrel': '🐿️',
  'Berry Fox': '🦊',
  'Magic Hare': '🐇✨',
  'Golden Rabbit': '🐰✨',
  'Resource Raccoon': '🦝',
  'Crystal Deer': '🦌💎',
  'Rainbow Unicorn': '🦄',
  'Phoenix Rabbit': '🐰🔥',
  'Cosmic Squirrel': '🐿️🌌',
  'Royal Bunny': '👑🐰',
  'Cyber Squirrel': '🤖🐿️',
  'Elemental Fox': '🔥🦊',
  'Celestial Hare': '🌟🐇',
  'Diamond Rabbit': '💎🐰',
  'Mecha Raccoon': '🦾🦝',
  'Enchanted Deer': '🦌✨',
  'Cosmic Unicorn': '🦄🌌',
  'Eternal Phoenix': '🔥🐰🔥',
  'Star Squirrel': '🌟🐿️',
};

export const MERGE_COMBINATIONS = {
  'Common Bunny': { name: 'Royal Bunny', emoji: '👑🐰' },
  'Nutty Squirrel': { name: 'Cyber Squirrel', emoji: '🤖🐿️' },
  'Berry Fox': { name: 'Elemental Fox', emoji: '🔥🦊' },
  'Magic Hare': { name: 'Celestial Hare', emoji: '🌟🐇' },
  'Golden Rabbit': { name: 'Diamond Rabbit', emoji: '💎🐰' },
  'Resource Raccoon': { name: 'Mecha Raccoon', emoji: '🦾🦝' },
  'Crystal Deer': { name: 'Enchanted Deer', emoji: '🦌✨' },
  'Rainbow Unicorn': { name: 'Cosmic Unicorn', emoji: '🦄🌌' },
  'Phoenix Rabbit': { name: 'Eternal Phoenix', emoji: '🔥🐰🔥' },
  'Cosmic Squirrel': { name: 'Star Squirrel', emoji: '🌟🐿️' },

  // New Merges
  'Royal Bunny': { name: 'Emperor Bunny', emoji: '👑🐰✨' },
  'Cyber Squirrel': { name: 'Quantum Squirrel', emoji: '🔬🤖🐿️' },
  'Elemental Fox': { name: 'Spirit Fox', emoji: '🌪️🔥🦊' },
  'Celestial Hare': { name: 'Astral Hare', emoji: '🌌🌟🐇' },
  'Diamond Rabbit': { name: 'Crystal Rabbit', emoji: '🔮💎🐰' },
  'Mecha Raccoon': { name: 'Titan Raccoon', emoji: '🦾🦝🚀' },
  'Enchanted Deer': { name: 'Mystic Deer', emoji: '🦌🔮✨' },
  'Cosmic Unicorn': { name: 'Galactic Unicorn', emoji: '🌌🦄✨' },
  'Eternal Phoenix': { name: 'Void Phoenix', emoji: '🔥🐰⚫' },
  'Star Squirrel': { name: 'Nebula Squirrel', emoji: '🌌🌟🐿️' },

  // Advanced Merges
  'Emperor Bunny': { name: 'Divine Bunny', emoji: '👑✨🐰🔱' },
  'Quantum Squirrel': { name: 'Infinity Squirrel', emoji: '♾️🔬🤖🐿️' },
  'Spirit Fox': { name: 'Ethereal Fox', emoji: '💨🌪️🔥🦊' },
  'Astral Hare': { name: 'Galactic Hare', emoji: '🌌✨🌟🐇' },
  'Crystal Rabbit': { name: 'Prism Rabbit', emoji: '🌈🔮💎🐰' },
  'Titan Raccoon': { name: 'Omega Raccoon', emoji: '🦾🚀🦝' },
  'Mystic Deer': { name: 'Arcane Deer', emoji: '🔮✨🦌🧙‍♂️' },
  'Galactic Unicorn': { name: 'Stellar Unicorn', emoji: '🌟🌌🦄' },
  'Void Phoenix': { name: 'Chaos Phoenix', emoji: '🔥⚫🐰💥' },
  'Nebula Squirrel': { name: 'Eclipse Squirrel', emoji: '🌒🌌🌟🐿️' },

  // Ultimate Merges
  'Divine Bunny': { name: 'Celestial Bunny', emoji: '👑🔱✨🐰' },
  'Infinity Squirrel': { name: 'Eternal Squirrel', emoji: '♾️🔬🐿️✨' },
  'Ethereal Fox': { name: 'Phantom Fox', emoji: '👻💨🌪️🔥🦊' },
  'Galactic Hare': { name: 'Cosmic Hare', emoji: '🌌✨🐇🌟' },
  'Prism Rabbit': { name: 'Spectrum Rabbit', emoji: '🌈✨🔮💎🐰' },
  'Omega Raccoon': { name: 'Alpha Raccoon', emoji: '🦾🚀✨🦝' },
  'Arcane Deer': { name: 'Sage Deer', emoji: '🔮🦌🧙‍♂️✨' },
  'Stellar Unicorn': { name: 'Nova Unicorn', emoji: '🌟🌌🦄✨' },
  'Chaos Phoenix': { name: 'Genesis Phoenix', emoji: '🔥💥🐰⚫' },
  'Eclipse Squirrel': { name: 'Solar Squirrel', emoji: '🌞🌒🌌🌟🐿️' },
};
